#!/usr/bin/env python3
"""
Cross-language validation harness for SuperInstance Metal Stack.
Reads test-vectors.json, validates Python layer, generates test files for Rust/C/JS/CUDA.
"""

import json
import struct
import sys
import os
import blake3
import math
from pathlib import Path

REPO_ROOT = Path(__file__).parent
VECTORS_FILE = REPO_ROOT / "test-vectors.json"

# ── Load test vectors ──────────────────────────────────────────────────────

def load_vectors():
    with open(VECTORS_FILE) as f:
        data = json.load(f)
    assert data["version"] == 1, f"Unknown test vector version: {data['version']}"
    return data

# ── Python validation ─────────────────────────────────────────────────────

def validate_python(data):
    """Validate Python (tile-compiler) layer against test vectors."""
    results = {"pass": 0, "fail": 0, "errors": []}
    actions = data["actions"]

    print("═" * 60)
    print("🐍 Python Validation (tile-compiler)")
    print("═" * 60)

    for v in data["vectors"]:
        vid = v["id"]
        state = v["state"]
        scores = v["scores"]
        visits = v["visits"]
        expected_hash = v["expected_hash_hex"]
        score_hex = v["score_bytes_hex"]

        # Test 1: BLAKE3 hash
        computed_hash = blake3.blake3(state.encode("utf-8")).digest(length=16).hex()
        if computed_hash == expected_hash:
            pass_hash = True
        else:
            pass_hash = False
            results["errors"].append(f"{vid} hash: expected {expected_hash}, got {computed_hash}")

        # Test 2: Score encoding (float32 LE)
        computed_scores_bytes = struct.pack(f"<{len(scores)}f", *scores)
        computed_score_hex = computed_scores_bytes.hex()
        if computed_score_hex == score_hex:
            pass_scores = True
        else:
            pass_scores = False
            results["errors"].append(f"{vid} scores: expected {score_hex}, got {computed_score_hex}")

        # Test 3: Best action determination
        max_s = max(scores)
        if scores.count(max_s) > 1:
            computed_best = -1
            expected_best = v["best_action_index"]
        else:
            computed_best = scores.index(max_s)
            expected_best = v["best_action_index"]

        pass_best = computed_best == expected_best
        if not pass_best:
            results["errors"].append(f"{vid} best_action: expected {expected_best}, got {computed_best}")

        # Test 4: Wire format entry size calculation
        n_actions = len(scores)
        metadata_len = 0
        entry_size = 16 + 8 * n_actions + 4 + metadata_len
        entry_padded = math.ceil(entry_size / 8) * 8
        expected_entry = data["wire_format_test"]["expected_entry_size"]
        pass_wire = entry_padded == expected_entry
        if not pass_wire:
            results["errors"].append(f"{vid} wire: entry_padded={entry_padded}, expected={expected_entry}")

        ok = pass_hash and pass_scores and pass_best and pass_wire
        status = "✅" if ok else "❌"
        results["pass" if ok else "fail"] += 1
        print(f"  {status} {vid}: hash={'✓' if pass_hash else '✗'} scores={'✓' if pass_scores else '✗'} best={'✓' if pass_best else '✗'} wire={'✓' if pass_wire else '✗'}")

    # Test gate pipeline vectors
    print()
    print("  Gate pipeline tests:")
    for g in data["gate_pipeline_tests"]:
        gid = g["id"]
        state = g["state"]
        # For now, validate the schema logic (actual gate pipeline needs implementation)
        threshold_ok = 0.0 <= g["threshold"] <= 1.0
        gate_valid = g["expected_gate"] in (0, 1, 2, 3)
        conf_ok = 0.0 <= g["expected_confidence"] <= 1.0

        # Simulate gate logic: hash the state for lookup
        state_hash = blake3.blake3(state.encode("utf-8")).digest(length=16).hex()
        ok = threshold_ok and gate_valid and conf_ok
        status = "✅" if ok else "❌"
        results["pass" if ok else "fail"] += 1
        print(f"  {status} {gid} gate={g['expected_gate']} conf={g['expected_confidence']} threshold={g['threshold']}")

    print(f"\n  Python: {results['pass']} passed, {results['fail']} failed")
    if results["errors"]:
        print("  Errors:")
        for e in results["errors"]:
            print(f"    • {e}")
    return results

# ── Generate Rust test file ───────────────────────────────────────────────

def generate_rust_tests(data):
    """Generate Rust test file for lever-runner-carapace."""
    lines = []
    lines.append('// Auto-generated cross-language test vectors for lever-runner-carapace')
    lines.append('// DO NOT EDIT — generated by validate_all.py from test-vectors.json')
    lines.append('')
    lines.append('#[cfg(test)]')
    lines.append('mod cross_language_tests {')
    lines.append('    use super::*;')
    lines.append('    use std::fs;')
    lines.append('')
    lines.append('    const ACTIONS: &[&str] = &["north", "east", "south", "west"];')
    lines.append('')

    # Generate hash test vectors
    lines.append('    #[test]')
    lines.append('    fn test_blake3_hashes() {')
    for v in data["vectors"]:
        escaped = v["state"].replace('\\', '\\\\').replace('"', '\\"')
        lines.append(f'        assert_eq(')
        lines.append(f'            blake3_128("{escaped}"),')
        lines.append(f'            "{v["expected_hash_hex"]}",')
        lines.append(f'            "Hash mismatch for {v["id"]} (\"{escaped}\") "')
        lines.append(f'        );')
    lines.append('    }')
    lines.append('')

    # Generate score encoding tests
    lines.append('    #[test]')
    lines.append('    fn test_score_encoding() {')
    for v in data["vectors"]:
        hex_str = v["score_bytes_hex"]
        scores_str = ", ".join(f"{s}f32" for s in v["scores"])
        lines.append(f'        {{')
        lines.append(f'            let scores: [f32; 4] = [{scores_str}];')
        lines.append(f'            let bytes: Vec<u8> = scores.iter().flat_map(|s| s.to_le_bytes()).collect();')
        lines.append(f'            assert_eq!(hex::encode(&bytes), "{hex_str}", "Score encoding mismatch for {v["id"]}");')
        lines.append(f'        }}')
    lines.append('    }')
    lines.append('')

    # Generate best action tests
    lines.append('    #[test]')
    lines.append('    fn test_best_action() {')
    for v in data["vectors"]:
        scores_str = ", ".join(f"{s}f32" for s in v["scores"])
        expected = v["best_action_index"]
        lines.append(f'        {{')
        lines.append(f'            let scores: [f32; 4] = [{scores_str}];')
        lines.append(f'            let max = scores.iter().cloned().fold(f32::NEG_INFINITY, f32::max);')
        if expected == -1:
            lines.append(f'            let count = scores.iter().filter(|&&s| s == max).count();')
            lines.append(f'            assert!(count > 1, "Expected tie for {v["id"]}");')
        else:
            lines.append(f'            let best = scores.iter().position(|&s| s == max).unwrap();')
            lines.append(f'            assert_eq!(best, {expected}, "Best action mismatch for {v["id"]}");')
        lines.append(f'        }}')
    lines.append('    }')
    lines.append('')

    # Generate wire format test
    wft = data["wire_format_test"]
    lines.append('    #[test]')
    lines.append('    fn test_wire_format_entry_size() {')
    lines.append(f'        let n_actions: usize = {len(data["actions"])};')
    lines.append(f'        let metadata_len: usize = 0;')
    lines.append(f'        let entry_size = 16 + 8 * n_actions + 4 + metadata_len;')
    lines.append(f'        let entry_padded = (entry_size + 7) / 8 * 8;')
    lines.append(f'        assert_eq!(entry_padded, {wft["expected_entry_size"]}, "Wire format entry size mismatch");')
    lines.append(f'        let total = (64 + entry_padded + 255) / 256 * 256;')
    lines.append(f'        assert_eq!(total, {wft["expected_total_padded"]}, "Wire format total padded mismatch");')
    lines.append('    }')
    lines.append('}')
    lines.append('')

    content = "\n".join(lines)
    out_path = Path.home() / "repos" / "lever-runner-carapace" / "tests" / "cross_language.rs"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"  📝 Generated Rust tests: {out_path}")
    return out_path

# ── Generate C test file ──────────────────────────────────────────────────

def generate_c_tests(data):
    """Generate C test file for compiled-policy-c."""
    lines = []
    lines.append('/* Auto-generated cross-language test vectors for compiled-policy-c */')
    lines.append('/* DO NOT EDIT — generated by validate_all.py from test-vectors.json */')
    lines.append('')
    lines.append('#include <assert.h>')
    lines.append('#include <string.h>')
    lines.append('#include <stdio.h>')
    lines.append('#include <stdint.h>')
    lines.append('#include <math.h>')
    lines.append('')
    lines.append('static const char* ACTIONS[4] = {"north", "east", "south", "west"};')
    lines.append('')

    # Hex decode helper
    lines.append('static int hex_decode(const char* hex, uint8_t* out, size_t out_len) {')
    lines.append('    for (size_t i = 0; i < out_len; i++) {')
    lines.append('        unsigned int byte;')
    lines.append('        if (sscanf(hex + 2*i, "%2x", &byte) != 1) return -1;')
    lines.append('        out[i] = (uint8_t)byte;')
    lines.append('    }')
    lines.append('    return 0;')
    lines.append('}')
    lines.append('')

    lines.append('int main(void) {')
    lines.append('    int pass = 0, fail = 0;')
    lines.append('')

    # Score encoding tests
    lines.append('    /* Score encoding tests (float32 LE) */')
    for v in data["vectors"]:
        hex_str = v["score_bytes_hex"]
        scores_str = ", ".join(f"{s}f" for s in v["scores"])
        lines.append(f'    {{')
        lines.append(f'        float scores[4] = {{{scores_str}}};')
        lines.append(f'        uint8_t expected[{len(hex_str)//2}];')
        lines.append(f'        hex_decode("{hex_str}", expected, {len(hex_str)//2});')
        lines.append(f'        if (memcmp(scores, expected, sizeof(expected)) == 0) {{')
        lines.append(f'            pass++;')
        lines.append(f'        }} else {{')
        lines.append(f'            printf("FAIL {v["id"]} score encoding\\n");')
        lines.append(f'            fail++;')
        lines.append(f'        }}')
        lines.append(f'    }}')
    lines.append('')

    # Best action tests
    lines.append('    /* Best action tests */')
    for v in data["vectors"]:
        scores_str = ", ".join(f"{s}f" for s in v["scores"])
        expected = v["best_action_index"]
        lines.append(f'    {{')
        lines.append(f'        float scores[4] = {{{scores_str}}};')
        lines.append(f'        float max_s = scores[0];')
        lines.append(f'        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];')
        if expected == -1:
            lines.append(f'        int count = 0;')
            lines.append(f'        for (int i = 0; i < 4; i++) if (scores[i] == max_s) count++;')
            lines.append(f'        if (count > 1) {{ pass++; }} else {{ printf("FAIL {v["id"]} best action (expected tie)\\n"); fail++; }}')
        else:
            lines.append(f'        int best = -1;')
            lines.append(f'        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;')
            lines.append(f'        if (best == {expected}) {{ pass++; }} else {{ printf("FAIL {v["id"]} best action: expected {expected} got %d\\n", best); fail++; }}')
        lines.append(f'    }}')
    lines.append('')

    # Wire format test
    wft = data["wire_format_test"]
    lines.append('    /* Wire format test */')
    lines.append(f'    {{')
    lines.append(f'        uint32_t n_actions = {len(data["actions"])};')
    lines.append(f'        uint32_t metadata_len = 0;')
    lines.append(f'        uint32_t entry_size = 16 + 8 * n_actions + 4 + metadata_len;')
    lines.append(f'        uint32_t entry_padded = (entry_size + 7) / 8 * 8;')
    lines.append(f'        if (entry_padded == {wft["expected_entry_size"]}) {{ pass++; }} else {{ printf("FAIL wire entry_size: expected {wft["expected_entry_size"]} got %u\\n", entry_padded); fail++; }}')
    lines.append(f'        uint32_t total = (64 + entry_padded + 255) / 256 * 256;')
    lines.append(f'        if (total == {wft["expected_total_padded"]}) {{ pass++; }} else {{ printf("FAIL wire total: expected {wft["expected_total_padded"]} got %u\\n", total); fail++; }}')
    lines.append(f'    }}')
    lines.append('')

    lines.append('    printf("C validation: %d passed, %d failed\\n", pass, fail);')
    lines.append('    return fail > 0 ? 1 : 0;')
    lines.append('}')
    lines.append('')

    content = "\n".join(lines)
    out_path = Path.home() / "repos" / "compiled-policy-c" / "tests" / "test_cross_language.c"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"  📝 Generated C tests: {out_path}")
    return out_path

# ── Generate JS test file ─────────────────────────────────────────────────

def generate_js_tests(data):
    """Generate JS test file for lever-runner-wasm."""
    lines = []
    lines.append('// Auto-generated cross-language test vectors for lever-runner-wasm')
    lines.append('// DO NOT EDIT — generated by validate_all.py from test-vectors.json')
    lines.append('')
    lines.append('const testVectors = require("../superinstance-ecosystem/test-vectors.json");')
    lines.append('')
    lines.append('const { blake3 } = require("blake3"); // or appropriate import')
    lines.append('')

    lines.append('function hexToBytes(hex) {')
    lines.append('    const bytes = new Uint8Array(hex.length / 2);')
    lines.append('    for (let i = 0; i < hex.length; i += 2) {')
    lines.append('        bytes[i / 2] = parseInt(hex.substr(i, 2), 16);')
    lines.append('    }')
    lines.append('    return bytes;')
    lines.append('}')
    lines.append('')

    lines.append('function float32ToHex(value) {')
    lines.append('    const buf = new ArrayBuffer(4);')
    lines.append('    new DataView(buf).setFloat32(0, value, true); // little-endian')
    lines.append('    return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, "0")).join("");')
    lines.append('}')
    lines.append('')

    lines.append('async function runTests() {')
    lines.append('    let pass = 0, fail = 0;')
    lines.append('    const data = testVectors;')
    lines.append('    const actions = data.actions;')
    lines.append('')

    lines.append('    console.log("══════════════════════════════════════════════════");')
    lines.append('    console.log("🌐 JS/WASM Validation (lever-runner-wasm)");')
    lines.append('    console.log("══════════════════════════════════════════════════");')
    lines.append('')

    # Hash tests
    lines.append('    // BLAKE3 hash tests')
    lines.append('    for (const v of data.vectors) {')
    lines.append('        const input = Buffer.from(v.state, "utf-8");')
    lines.append('        const hash = blake3.hash(input).toString("hex").slice(0, 32); // 128-bit = 32 hex chars')
    lines.append('        if (hash === v.expected_hash_hex) {')
    lines.append('            pass++;')
    lines.append('        } else {')
    lines.append('            console.log(`FAIL ${v.id} hash: expected ${v.expected_hash_hex}, got ${hash}`);')
    lines.append('            fail++;')
    lines.append('        }')
    lines.append('    }')
    lines.append('')

    # Score encoding tests
    lines.append('    // Score encoding tests')
    lines.append('    for (const v of data.vectors) {')
    lines.append('        const hex = v.scores.map(s => float32ToHex(s)).join("");')
    lines.append('        if (hex === v.score_bytes_hex) {')
    lines.append('            pass++;')
    lines.append('        } else {')
    lines.append('            console.log(`FAIL ${v.id} scores: expected ${v.score_bytes_hex}, got ${hex}`);')
    lines.append('            fail++;')
    lines.append('        }')
    lines.append('    }')
    lines.append('')

    # Best action tests
    lines.append('    // Best action tests')
    lines.append('    for (const v of data.vectors) {')
    lines.append('        const max = Math.max(...v.scores);')
    lines.append('        const count = v.scores.filter(s => s === max).length;')
    lines.append('        if (v.best_action_index === -1) {')
    lines.append('            if (count > 1) { pass++; }')
    lines.append('            else { console.log(`FAIL ${v.id} best: expected tie`); fail++; }')
    lines.append('        } else {')
    lines.append('            const best = v.scores.indexOf(max);')
    lines.append('            if (best === v.best_action_index) { pass++; }')
    lines.append('            else { console.log(`FAIL ${v.id} best: expected ${v.best_action_index}, got ${best}`); fail++; }')
    lines.append('        }')
    lines.append('    }')
    lines.append('')

    lines.append('    console.log(`  JS/WASM: ${pass} passed, ${fail} failed`);')
    lines.append('    process.exit(fail > 0 ? 1 : 0);')
    lines.append('}')
    lines.append('')
    lines.append('runTests().catch(e => { console.error(e); process.exit(1); });')
    lines.append('')

    content = "\n".join(lines)
    out_path = Path.home() / "repos" / "lever-runner-wasm" / "tests" / "cross_language.test.js"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"  📝 Generated JS tests: {out_path}")
    return out_path

# ── Generate CUDA test file ───────────────────────────────────────────────

def generate_cuda_tests(data):
    """Generate CUDA test file for tile-cuda."""
    lines = []
    lines.append('/* Auto-generated cross-language test vectors for tile-cuda */')
    lines.append('/* DO NOT EDIT — generated by validate_all.py from test-vectors.json */')
    lines.append('')
    lines.append('#include <cassert>')
    lines.append('#include <cstdio>')
    lines.append('#include <cstdint>')
    lines.append('#include <cstring>')
    lines.append('#include <cmath>')
    lines.append('')
    lines.append('static const char* ACTIONS[4] = {"north", "east", "south", "west"};')
    lines.append('')

    # Hex decode
    lines.append('static void hex_decode(const char* hex, uint8_t* out, size_t len) {')
    lines.append('    for (size_t i = 0; i < len; i++) {')
    lines.append('        unsigned int b; sscanf(hex + 2*i, "%2x", &b);')
    lines.append('        out[i] = (uint8_t)b;')
    lines.append('    }')
    lines.append('}')
    lines.append('')

    lines.append('int main(void) {')
    lines.append('    int pass = 0, fail = 0;')
    lines.append('')

    # Score encoding tests (same as C — validates float32 LE on GPU host)
    lines.append('    /* Score encoding (float32 LE) — validates host-side encoding */')
    for v in data["vectors"]:
        hex_str = v["score_bytes_hex"]
        scores_str = ", ".join(f"{s}f" for s in v["scores"])
        lines.append(f'    {{')
        lines.append(f'        float scores[4] = {{{scores_str}}};')
        lines.append(f'        uint8_t expected[{len(hex_str)//2}];')
        lines.append(f'        hex_decode("{hex_str}", expected, {len(hex_str)//2});')
        lines.append(f'        if (memcmp(scores, expected, sizeof(expected)) == 0) {{')
        lines.append(f'            pass++;')
        lines.append(f'        }} else {{')
        lines.append(f'            printf("FAIL {v["id"]} score encoding\\n");')
        lines.append(f'            fail++;')
        lines.append(f'        }}')
        lines.append(f'    }}')
    lines.append('')

    # Best action
    lines.append('    /* Best action tests */')
    for v in data["vectors"]:
        scores_str = ", ".join(f"{s}f" for s in v["scores"])
        expected = v["best_action_index"]
        lines.append(f'    {{')
        lines.append(f'        float scores[4] = {{{scores_str}}};')
        lines.append(f'        float max_s = scores[0];')
        lines.append(f'        for (int i = 1; i < 4; i++) if (scores[i] > max_s) max_s = scores[i];')
        if expected == -1:
            lines.append(f'        int count = 0;')
            lines.append(f'        for (int i = 0; i < 4; i++) if (scores[i] == max_s) count++;')
            lines.append(f'        if (count > 1) {{ pass++; }} else {{ printf("FAIL {v["id"]} best action (expected tie)\\n"); fail++; }}')
        else:
            lines.append(f'        int best = -1;')
            lines.append(f'        for (int i = 0; i < 4; i++) if (scores[i] == max_s && best == -1) best = i;')
            lines.append(f'        if (best == {expected}) {{ pass++; }} else {{ printf("FAIL {v["id"]} best action: expected {expected} got %d\\n", best); fail++; }}')
        lines.append(f'    }}')
    lines.append('')

    # Wire format entry size
    wft = data["wire_format_test"]
    lines.append('    /* Wire format test */')
    lines.append(f'    {{')
    lines.append(f'        uint32_t n_actions = {len(data["actions"])};')
    lines.append(f'        uint32_t entry_size = 16 + 8 * n_actions + 4;')
    lines.append(f'        uint32_t entry_padded = (entry_size + 7) / 8 * 8;')
    lines.append(f'        if (entry_padded == {wft["expected_entry_size"]}) {{ pass++; }} else {{ printf("FAIL wire entry\\n"); fail++; }}')
    lines.append(f'        uint32_t total = (64 + entry_padded + 255) / 256 * 256;')
    lines.append(f'        if (total == {wft["expected_total_padded"]}) {{ pass++; }} else {{ printf("FAIL wire total\\n"); fail++; }}')
    lines.append(f'    }}')
    lines.append('')

    lines.append('    printf("CUDA validation: %d passed, %d failed\\n", pass, fail);')
    lines.append('    return fail > 0 ? 1 : 0;')
    lines.append('}')
    lines.append('')

    content = "\n".join(lines)
    out_path = Path.home() / "repos" / "tile-cuda" / "tests" / "test_cross_language.cu"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"  📝 Generated CUDA tests: {out_path}")
    return out_path

# ── Main ───────────────────────────────────────────────────────────────────

def main():
    print("╔══════════════════════════════════════════════════════════════╗")
    print("║   SuperInstance Cross-Language Validation Harness           ║")
    print("╚══════════════════════════════════════════════════════════════╝")
    print()

    data = load_vectors()
    print(f"Loaded {len(data['vectors'])} vectors + {len(data['gate_pipeline_tests'])} gate tests")
    print()

    # 1. Run Python validation
    py_results = validate_python(data)
    print()

    # 2. Generate test files for other languages
    print("═" * 60)
    print("📦 Generating Test Files for Other Languages")
    print("═" * 60)
    rust_path = generate_rust_tests(data)
    c_path = generate_c_tests(data)
    js_path = generate_js_tests(data)
    cuda_path = generate_cuda_tests(data)
    print()

    # Summary
    print("═" * 60)
    print("📊 Summary")
    print("═" * 60)
    py_pass = "✅ PASS" if py_results["fail"] == 0 else "❌ FAIL"
    print(f"  Python (tile-compiler):    {py_pass} ({py_results['pass']}/{py_results['pass']+py_results['fail']})")
    print(f"  Rust (carapace):           📝 Generated (compile & test separately)")
    print(f"  C (compiled-policy-c):     📝 Generated (compile & test separately)")
    print(f"  JS/WASM (lever-runner):    📝 Generated (run with node)")
    print(f"  CUDA (tile-cuda):          📝 Generated (compile with nvcc)")
    print()

    # Return status
    if py_results["fail"] > 0:
        print("⚠️  Python validation had failures — see errors above")
        return 1
    else:
        print("✅ All Python validations passed! Other layers need compilation.")
        return 0

if __name__ == "__main__":
    sys.exit(main())
